# Generated by Django 4.2.7 on 2023-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_studentreg_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
