# Generated by Django 4.2.7 on 2023-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20)),
                ('course_img', models.FileField(upload_to='eduapp/static/assets/images')),
                ('course_type', models.CharField(choices=[('DigitalMarketing', 'DigitalMarketing'), ('Python', 'Python'), ('Flutter', 'Flutter'), ('Java', 'Java'), ('DataScience', 'DataScience'), ('MachineLearning', 'MachineLearning'), ('SoftwareTesting', 'SoftwareTesting')], max_length=30)),
                ('institution_name', models.CharField(max_length=30)),
                ('course_desc', models.CharField(max_length=500)),
                ('from_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=30)),
                ('to_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=30)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
