# Generated by Django 4.2.7 on 2023-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0006_remove_coursemodel_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=30)),
                ('course_img', models.FileField(upload_to='eduapp/static/assets/images')),
                ('institution_name', models.CharField(max_length=30)),
                ('from_day', models.CharField(max_length=30)),
                ('to_day', models.CharField(max_length=30)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
