# Generated by Django 4.2.7 on 2023-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0007_course_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrolled',
            name='student_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
