# Generated by Django 4.2.7 on 2023-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0008_course_enrolled_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=30)),
                ('assignment', models.CharField(max_length=500)),
            ],
        ),
    ]
