# Generated by Django 4.2.7 on 2023-12-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0009_add_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_assignment',
            name='course_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
